################################################################################
# Chullipparambil, Chinnu Padman
# Class Account: masc1445
# CS 570, Summer 2014
# Assignment #2, Analysis of Page Replacement Algorithms.
# Filename : Makefile
################################################################################
EXEC = a2
CC = g++       

$(EXEC):
	$(CC) -o $(EXEC) a2_functions.cpp a2.cpp
	rm -f *.o

clean:
	rm -f *.o core a.out $(EXEC)

##################################[ EOF: Makefile ]#############################
