################################################################################
# Chullipparambil, Chinnu Padman
# Class Account: masc1445
# CS 570, Summer 2014
# Assignment #1, Program that manages multiple threads writing to a shared file.
# Filename : Makefile
################################################################################
EXEC = sem
CC = g++       

$(EXEC):
	$(CC) -o $(EXEC) sem.cpp -lrt
	rm -f *.o

clean:
	rm -f *.o core a.out $(EXEC)

##################################[ EOF: Makefile ]#############################
