################################################################################
# Chullipparambil, Chinnu Padman
# Class Account: masc1445
# CS 570, Summer 2014
# Assignment #3, Design and implement a multiple process, time viewer.
# Filename : Makefile
################################################################################
EXEC = a3
CC = g++       

$(EXEC):
	$(CC) -o $(EXEC) a3.cpp
	rm -f *.o

clean:
	rm -f *.o core a.out $(EXEC)

##################################[ EOF: Makefile ]#############################
